# Compose file for production.

volumes:
  db_data:
  storage:

services:
  snipeit:
    # image: snipe/snipe-it:${APP_VERSION:-v7.0.11}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snipe-it
    restart: unless-stopped
    volumes:
      - storage:/var/lib/snipeit
    ports:
      - "${APP_PORT:-8000}:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  nginx:
    container_name: snipe-it-nginx
    image: "nginx:latest"
    restart: unless-stopped
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - snipeit

  db:
    image: mariadb:11.5.2
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#compose-file-example
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5
